/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

declare module "vue" {
  export interface GlobalComponents {
    CardItem: typeof import("./src/components/CardItem.vue")["default"];
    CardList: typeof import("./src/components/CardList.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    VanBadge: typeof import("vant/es")["Badge"];
    VanButton: typeof import("vant/es")["Button"];
    VanCell: typeof import("vant/es")["Cell"];
    VanCol: typeof import("vant/es")["Col"];
    VanDropdownItem: typeof import("vant/es")["DropdownItem"];
    VanDropdownMenu: typeof import("vant/es")["DropdownMenu"];
    VanField: typeof import("vant/es")["Field"];
    VanIcon: typeof import("vant/es")["Icon"];
    VanImage: typeof import("vant/es")["Image"];
    VanList: typeof import("vant/es")["List"];
    VanNavBar: typeof import("vant/es")["NavBar"];
    VanPopover: typeof import("vant/es")["Popover"];
    VanRate: typeof import("vant/es")["Rate"];
    VanRow: typeof import("vant/es")["Row"];
    VanSearch: typeof import("vant/es")["Search"];
    VanSwipe: typeof import("vant/es")["Swipe"];
    VanSwipeItem: typeof import("vant/es")["SwipeItem"];
    VanTab: typeof import("vant/es")["Tab"];
    VanTabbar: typeof import("vant/es")["Tabbar"];
    VanTabbarItem: typeof import("vant/es")["TabbarItem"];
    VanTabs: typeof import("vant/es")["Tabs"];
    VanTag: typeof import("vant/es")["Tag"];
  }
}
